version: '3'
services:
  signer:
    image: cartesi/ethsigner:0.1.0
    command: "--chain-id=1 --downstream-http-host=mainnet.infura.io --downstream-http-port=443 --http-cors-origins=\"http://localhost:3000,https://explorer.cartesi.io\" --downstream-http-tls-enabled --downstream-http-path=/v3/${PROJECT_ID:?PROJECT_ID undefined, please set up an application at Infura}"
    ports:
      - 8545:8545
  
  dispatcher:
    image: cartesi/pos:0.1.0-beta.12
    restart: always
    environment:
      RUST_LOG: dispatcher=trace,transaction=trace,configuration=trace,utils=trace,state=trace,descartes=trace
      WEB3_PROVIDER_URI: http://signer:8545
      CHAIN_NAME: mainnet
      QUERY_PORT: 3001
      ETHEREUM_HOST: signer
      ETHEREUM_PORT: 8545
      DOCKER: "TRUE"
