version: '3'
services:
  alice_signer:
    image: cartesi/ethsigner:latest
    command: "--chain-id=31337 --downstream-http-host=host.docker.internal --downstream-http-port=8545 --http-listen-port=8546"
    expose:
      - 8546
    networks:
      ethereum: {}
      alice:
        aliases:
          - signer
  
  alice_dispatcher:
    image: cartesi/pos:latest
    restart: always
    environment:
      RUST_LOG: dispatcher=info,transaction=info,configuration=trace,utils=trace,state=info
      WEB3_PROVIDER_URI: http://signer:8546
      CHAIN_NAME: localhost_31337
      QUERY_PORT: 3001
      ETHEREUM_HOST: signer
      ETHEREUM_PORT: 8546
      DOCKER: "TRUE"
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - alice_data:/opt/cartesi/srv/pos
    networks:
      ethereum: {}
      alice:
        aliases:
          - dispatcher

  bob_signer:
    image: cartesi/ethsigner:latest
    command: "--chain-id=31337 --downstream-http-host=host.docker.internal --downstream-http-port=8545 --http-listen-port=8547"
    expose:
      - 8547
    networks:
      ethereum: {}
      bob:
        aliases:
          - signer
  
  bob_dispatcher:
    image: cartesi/pos:latest
    restart: always
    environment:
      RUST_LOG: dispatcher=info,transaction=info,configuration=trace,utils=trace,state=info
      WEB3_PROVIDER_URI: http://signer:8547
      CHAIN_NAME: localhost_31337
      QUERY_PORT: 3001
      ETHEREUM_HOST: signer
      ETHEREUM_PORT: 8547
      DOCKER: "TRUE"
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - bob_data:/opt/cartesi/srv/pos
    networks:
      bob:
        aliases:
          - dispatcher

volumes:
  alice_data:
  bob_data:

networks:
  ethereum:
  alice:
  bob:
