version: '3'
services:
  signer:
    image: cartesi/ethsigner:0.1.1
    command: "--chain-id=1 --downstream-http-host=eth.cartesi.io --downstream-http-port=443 --http-cors-origins=\"http://localhost:3000,https://explorer.cartesi.io\" --downstream-http-tls-enabled"
    volumes:
      - wallet:/root/.ethereum

  dispatcher:
    image: cartesi/pos:0.1.0-beta.22
    restart: always
    environment:
      RUST_LOG: dispatcher=error,transaction=error,configuration=error,utils=error,state=error,worker=error,pos=info
      WEB3_PROVIDER_URI: http://signer:8545
      CHAIN_NAME: mainnet
      QUERY_PORT: 3001
      ETHEREUM_HOST: signer
      ETHEREUM_PORT: 8545
      DOCKER: "TRUE"

volumes:
  wallet:
