version: '3'
services:
  signer:
    image: cartesi/ethsigner:latest
    command: "--chain-id=31337 --downstream-http-host=host.docker.internal --http-cors-origins=\"*\" --downstream-http-port=7545 --http-listen-port=8545"
    expose:
      - 8545
    ports:
      - 8545:8545
  
  dispatcher:
    image: cartesi/pos:latest
    restart: always
    environment:
      RUST_LOG: dispatcher=info,transaction=info,configuration=trace,utils=trace,state=info
      WEB3_PROVIDER_URI: http://signer:8545
      CHAIN_NAME: localhost
      QUERY_PORT: 3001
      ETHEREUM_HOST: signer
      ETHEREUM_PORT: 8545
      DOCKER: "TRUE"
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
