[package]
description = "Cartesi Proof of Stake (Cache)"
homepage = "https://cartesi.io"
name = "pos"
version = "0.1.0"
authors = ["Cartesi Team"]

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
log = "0.4"
env_logger = "0.6.0"
ethereum-types = "0.9.0"
ethabi = "12.0.0"
serde_json = "1.0"
serde = "1.0.0"
serde_derive = "1.0.0"
protobuf = "2"
rust-crypto = "0.2.36"
hex = "0.4.0"
