name: Build
on: [push]
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly

            - run: yarn install
            - run: yarn prettier
            - run: yarn build
            - run: yarn test
            - run: forge test -vvv
