name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: yarn install
      - run: yarn test
