name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - run: npx buidler typechain
      - run: yarn test

      - name: Build docker image
        run: docker build . -t cartesi/pos

      - name: Push image to Docker Hub
        run: |
          docker tag cartesi/pos cartesi/pos:${GITHUB_REF:11}
          docker push cartesi/pos
          docker push cartesi/pos:${GITHUB_REF:11}
        if:  startsWith(github.ref, 'refs/tags/v')
